### ISSUE TITLE
named export error

### ISSUE THREAD

**Issue by halindraprakoso** [carbon-design-system/carbon-components-svelte#1391]
hello,
I'm suddenly having this error during the build and I couldn't figure out the cause and how to fix it.
```js

file:///Users/halindra/Documents/Projects/my-project/.svelte-kit/output/server/immutable/chunks/BaseChart-8547cc7c.js:1
import { Modal as Modal$2 } from "carbon-components";
         ^^^^^
SyntaxError: Named export 'Modal' not found. The requested module 'carbon-components' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'carbon-components';
const { Modal: Modal$2 } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async Promise.all (index 3)
    at async respond$1 (file:///Users/halindra/Documents/Projects/my-project/.svelte-kit/output/server/index.js:1826:13)
    at async resolve (file:///Users/halindra/Documents/Projects/my-project/.svelte-kit/output/server/index.js:2188:114)
    at async e (file:///Users/halindra/Documents/Projects/my-project/node_modules/.pnpm/trpc-sveltekit@2.1.1_sgykaiqo6gckgqqezyzpwtzhty/node_modules/trpc-sveltekit/dist/index.modern.js:1:605)
    at async Object.handle (file:///Users/halindra/Documents/Projects/my-project/.svelte-kit/output/server/immutable/chunks/hooks-12fd823b.js:2067:20)
    at async respond (file:///Users/halindra/Documents/Projects/my-project/.svelte-kit/output/server/index.js:2143:22)
[vite-plugin-svelte-kit] 500 /app/finance/payments
file:///Users/halindra/Documents/Projects/my-project/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.369_svelte@3.49.0+vite@2.9.14/node_modules/@sveltejs/kit/dist/vite.js:1122
				throw new Error(format_error(details));
				      ^

Error: 500 /app/finance/payments
    at file:///Users/halindra/Documents/Projects/my-project/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.369_svelte@3.49.0+vite@2.9.14/node_modules/@sveltejs/kit/dist/vite.js:1122:11
    at save (file:///Users/halindra/Documents/Projects/my-project/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.369_svelte@3.49.0+vite@2.9.14/node_modules/@sveltejs/kit/dist/vite.js:1341:4)
    at visit (file:///Users/halindra/Documents/Projects/my-project/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.369_svelte@3.49.0+vite@2.9.14/node_modules/@sveltejs/kit/dist/vite.js:1232:3) {
  code: 'PLUGIN_ERROR',
  plugin: 'vite-plugin-svelte-kit',
  hook: 'writeBundle'
}

Node.js v17.7.2
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by halindraprakoso** [comment]
turns out it works without the library too. I just removed it and it seems fine. I wonder why I had it installed.
sorry for bothering
