### ISSUE TITLE
Tabs do not work, issues incorrect context to Tab

### ISSUE THREAD

**Issue by geoidesic** [carbon-design-system/carbon-components-svelte#1827]
Steps to reproduce:
## 1. Create two tabs:

```
	import { Tab, TabContent, Tabs } from 'carbon-components-svelte';
        let selected = 0;
...

<Tabs bind:selected>
  <Tab label="One" />
  <Tab label="Two" />
  <svelte:fragment slot="content">
     {#if selected == 0}
	<TabContent>blah</TabContent>
     {/if}
     {#if selected == 1}
	<TabContent>blah blah</TabContent>
     {/if}
```
## 2. Then click tab Two, then tab One, which produces the error below

I also added in some logging to Tab.svelte, which is included in the error output below:
```
$: {
		console.log('index', index);
		console.log('id', id);
		console.log('$selectedContent', $selectedContent);
		console.log('$contentById', $contentById);
		console.log('$tabs', $tabs);
		console.log('$tabs[index]', $tabs[index]);
		console.log('$tabs[index].id', $tabs[index].id);

		tabId = $tabs[index]?.id;
	}
```

## Error Logs
```
index 0
TabContent.svelte:15 id ccs-0.nbk9hrzvr6h
TabContent.svelte:16 $selectedContent undefined
TabContent.svelte:17 $contentById {ccs-0.nbk9hrzvr6h: {…}}
TabContent.svelte:18 $tabs (2) [{…}, {…}]
TabContent.svelte:19 $tabs[index] {id: 'ccs-0.4pt3igj6u3a', label: 'Background', disabled: false, index: 0}
TabContent.svelte:20 $tabs[index].id ccs-0.4pt3igj6u3a
TabContent.svelte:14 index 0
TabContent.svelte:15 id ccs-0.nbk9hrzvr6h
TabContent.svelte:16 $selectedContent ccs-0.nbk9hrzvr6h
TabContent.svelte:17 $contentById {ccs-0.nbk9hrzvr6h: {…}}
TabContent.svelte:18 $tabs (2) [{…}, {…}]
TabContent.svelte:19 $tabs[index] {id: 'ccs-0.4pt3igj6u3a', label: 'Background', disabled: false, index: 0}
TabContent.svelte:20 $tabs[index].id ccs-0.4pt3igj6u3a
Tabs.svelte:91 currentIndex 0
Tabs.svelte:92 prevIndex -1
SceneSettings.svelte:1 files (4) [{…}, {…}, {…}, {…}]
Tabs.svelte:91 currentIndex 1
Tabs.svelte:92 prevIndex 0
Tabs.svelte:95 dispatch change
SceneSettings.svelte:176 selected 1
TabContent.svelte:14 index 1
TabContent.svelte:15 id ccs-0.8kuxkbktagu
TabContent.svelte:16 $selectedContent ccs-0.nbk9hrzvr6h
TabContent.svelte:17 $contentById {ccs-0.nbk9hrzvr6h: {…}, ccs-0.8kuxkbktagu: {…}}
TabContent.svelte:18 $tabs (2) [{…}, {…}]
TabContent.svelte:19 $tabs[index] {id: 'ccs-0.w15q3grr4o', label: 'Grid', disabled: false, index: 1}
TabContent.svelte:20 $tabs[index].id ccs-0.w15q3grr4o
TabContent.svelte:14 index 1
TabContent.svelte:15 id ccs-0.8kuxkbktagu
TabContent.svelte:16 $selectedContent ccs-0.8kuxkbktagu
TabContent.svelte:17 $contentById {ccs-0.nbk9hrzvr6h: {…}, ccs-0.8kuxkbktagu: {…}}
TabContent.svelte:18 $tabs (2) [{…}, {…}]
TabContent.svelte:19 $tabs[index] {id: 'ccs-0.w15q3grr4o', label: 'Grid', disabled: false, index: 1}
TabContent.svelte:20 $tabs[index].id ccs-0.w15q3grr4o
TabContent.svelte:14 index 1
TabContent.svelte:15 id ccs-0.8kuxkbktagu
TabContent.svelte:16 $selectedContent ccs-0.nbk9hrzvr6h
TabContent.svelte:17 $contentById {ccs-0.nbk9hrzvr6h: {…}, ccs-0.8kuxkbktagu: {…}}
TabContent.svelte:18 $tabs (2) [{…}, {…}]
TabContent.svelte:19 $tabs[index] {id: 'ccs-0.w15q3grr4o', label: 'Grid', disabled: false, index: 1}
TabContent.svelte:20 $tabs[index].id ccs-0.w15q3grr4o
Tabs.svelte:91 currentIndex 0
Tabs.svelte:92 prevIndex 1
Tabs.svelte:95 dispatch change
SceneSettings.svelte:176 selected 0
TabContent.svelte:14 index 2
TabContent.svelte:15 id ccs-0.we184glu2r
TabContent.svelte:16 $selectedContent ccs-0.nbk9hrzvr6h
TabContent.svelte:17 $contentById {ccs-0.nbk9hrzvr6h: {…}, ccs-0.8kuxkbktagu: {…}, ccs-0.we184glu2r: {…}}
TabContent.svelte:18 $tabs (2) [{…}, {…}]
TabContent.svelte:19 $tabs[index] undefined
proxy.js?v=f8e1c0c0:15 [HMR][Svelte] Unrecoverable HMR error in <TabContent>: next update will trigger a full reload
logError @ proxy.js?v=f8e1c0c0:15
Proxy<TabContent> @ proxy.js?v=f8e1c0c0:380
create_if_block_1 @ SceneSettings.svelte?t=1697020961729:131
update @ SceneSettings.svelte:176
update_slot_base @ utils.js:203
update @ Tabs.svelte:128
update @ scheduler.js:119
flush @ scheduler.js:79
Promise.then (async)
schedule_update @ scheduler.js:20
make_dirty @ Component.js:81
(anonymous) @ Component.js:129
update @ Tabs.svelte:51
click_handler_1 @ Tab.svelte:43
(anonymous) @ dom.js:369
TabContent.svelte:20 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'id')
    at $$self.$$.update (TabContent.svelte:20:47)
    at init (Component.js:134:5)
    at new TabContent (TabContent.svelte:22:27)
    at createProxiedComponent (svelte-hooks.js?v=f8e1c0c0:341:9)
    at new ProxyComponent (proxy.js?v=f8e1c0c0:242:7)
    at new Proxy<TabContent> (proxy.js?v=f8e1c0c0:349:11)
    at create_if_block_1 (SceneSettings.svelte?t=1697020961729:131:15)
    at Object.update [as p] (SceneSettings.svelte:176:288)
    at update_slot_base (utils.js:203:8)
    at Object.update [as p] (Tabs.svelte:128:49)
    ```

**Comment by brunnerh** [comment]
That is not how you use that component. The `TabContent` components are shown/hidden automatically based on the selected tab, by removing them dynamically, you mess with this system.

Example [from docs](https://carbon-components-svelte.onrender.com/components/Tabs):
```svelte
<Tabs>
  <Tab label="Tab label 1" />
  <Tab label="Tab label 2" />
  <Tab label="Tab label 3" />
  <svelte:fragment slot="content">
    <TabContent>Content 1</TabContent>
    <TabContent>Content 2</TabContent>
    <TabContent>Content 3</TabContent>
  </svelte:fragment>
</Tabs>
```

**Comment by geoidesic** [comment]
Well the problem with that is that the tabs only hide and show using "visibility" in CSS but I don't want them to be rendered until the tab is clicked. Is there another way to achieve that besides my example?

**Comment by brunnerh** [comment]
Put the `{#if}` inside the `TabContent`.

**Comment by geoidesic** [comment]
Why didn't I think of that?
