### ISSUE TITLE
Broken example: carbon + routify

### ISSUE THREAD

**Issue by miedzikd** [carbon-design-system/carbon-components-svelte#456]
Hey!

I am trying to create a new project with this example (https://github.com/IBM/carbon-components-svelte/tree/master/examples/routify) 

Unfortunately, after installing the dependencies and running the command `yarn dev` I see this error:
```node
dm@DESKTOP-NU9S96U ~/D/P/J/m/avt-mts-frontend > yarn dev
yarn run v1.22.5
$ run-p dev:*
$ routify
$ rollup -cw
[Routify] Watching src/pages
[Routify] Generated routes in 4 ms
[!] Error: ENOENT: no such file or directory, rmdir 'dist'
Error: ENOENT: no such file or directory, rmdir 'dist'
    at Object.rmdirSync (fs.js:684:3)
    at createRollupConfigs (/home/dm/Documents/Projects/JW/mts/avt-mts-frontend/rollup.config.js:35:26)
    at Object.<anonymous> (/home/dm/Documents/Projects/JW/mts/avt-mts-frontend/rollup.config.js:135:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.require.extensions.(anonymous function) [as .js] (/home/dm/Documents/Projects/JW/mts/avt-mts-frontend/node_modules/rollup/dist/shared/loadConfigFile.js:508:20)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)

```

**Comment by miedzikd** [comment]
As temp solution I just create empty directory `dist` ... Then I see this:

```node
dm@DESKTOP-NU9S96U ~/D/P/J/m/avt-mts-frontend (remove-sapper) [SIGINT]> yarn dev
yarn run v1.22.5
$ run-p dev:*
$ routify
$ rollup -cw
[Routify] Watching src/pages
[Routify] Generated routes in 3 ms
[spassr] Serving spa on http://localhost:5000
[spassr] Serving ssr on http://localhost:5005
```

but when I open http://localhost:5000 I don't see anything... loading is never finished

**Comment by metonym** [comment]
We no longer have a Routify example
